FROM rust:1-bullseye AS builder
COPY . .
RUN cd rustex-api && cargo build -r && cargo install --path .

FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y libpq-dev build-essential && rm -rf /var/lib/apt/lists/*
COPY --from=builder /.env .
COPY --from=builder /usr/local/cargo/bin/rustex-api /usr/local/bin/rustex-api
CMD ["rustex-api"]

