services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
