[package]
name = "rustex-test"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = { workspace = true }
tokio = { workspace = true }
reqwest = { version = "0.12.12", features = ["json", "native-tls"] }
serde = { workspace = true }
serde_json = { workspace = true }
rand = "0.9.0"

