[package]
name = "rustex-micro"
version = "0.0.0"
authors = ["Diego Pardo"]
edition = "2021"

[lib]
name = "rpc_clients"
path = "src/lib.rs"

[[bin]]
name = "time_service"
path = "src/time_service.rs"

[[bin]]
name = "match_service"
path = "src/match_service.rs"

[dependencies]
anyhow = "1.0.95"
futures = "0.3.31"
log = { workspace = true }
paste = "1.0.15"
rustex-core = { workspace = true }
tarpc = { version = "0.35.0", features = ["full"] }
tokio = { workspace = true }
