[package]
name = "rustex-errors"
version = "0.0.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
diesel = { workspace = true }
diesel-async = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
tarpc = { workspace = true }
tokio = { workspace = true }